# These are supported funding model platforms

github:[R.C YADAV,REKHA YADAV, NIRMAL YADAV]
patreon: -
open_collective: SHUBHAM YYADAV
ko_fi: SHYBEAST
tidelift: YOUTUBE
community_bridge: //NOTHING
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: https://www.youtube.com/channel/UCiM4TukTG-b8iOAU1UZorXQ
custom:[https://www.youtube.com/channel/UCiM4TukTG-b8iOAU1UZorXQ]
